[#macro body]
    [@d.form name="userEditForm" theme="form"]
        [@d.formhead]
        <h4>用户[#if (user.id)??]编辑[#else]新建[/#if]</h4>
        [/@]
        [@d.formbody]
            [@d.textfield name="user.username" label="用户名" required="true" value=user.username!/]
        [/@]
        [@d.formfooter]
            [@d.button cssClass="btn-default" value="关闭"/]
            [@d.submit cssClass="btn-primary" value="提交"/]
        [/@]
    [/@]
[/#macro]
