INSERT INTO SYS_ROLES (ID,DESCRIPTION,NAME,ENABLED,CREATED_AT,UPDATED_AT) SELECT SEQ_SYS_ROLES.NEXTVAL,'超级管理员','admin',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP() FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_ROLES T2 WHERE T2.NAME='admin');
INSERT INTO SYS_ROLES (ID,DESCRIPTION,NAME,ENABLED,CREATED_AT,UPDATED_AT) SELECT SEQ_SYS_ROLES.NEXTVAL,'管理员','manager',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP() FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_ROLES T2 WHERE T2.NAME='manager');
INSERT INTO SYS_ROLES (ID,DESCRIPTION,NAME,ENABLED,CREATED_AT,UPDATED_AT) SELECT SEQ_SYS_ROLES.NEXTVAL,'用户','user',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP() FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_ROLES T2 WHERE T2.NAME='user');
INSERT INTO SYS_USERS (ID,DESCRIPTION,NAME,PASSWORD,ENABLED,ROLE_ID,EMAIL,CREATED_AT,UPDATED_AT)
SELECT 1,'admin@pt.sisi','111111',1,SELECT ID FROM SYS_ROLES WHERE NAME='admin','admin@pt.sisi',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP() FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_USERS T1 WHERE T1.ID=1);
DROP SEQUENCE SEQ_SYS_USERS;
CREATE SEQUENCE SEQ_SYS_USERS START WITH 2 INCREMENT BY 1;