INSERT INTO SYS_ROLES (ID,DESCRIPTION,NAME) SELECT SEQ_SYS_ROLES.NEXTVAL,'超级管理员','admin' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_ROLES T2 WHERE T2.NAME='admin');
INSERT INTO SYS_ROLES (ID,DESCRIPTION,NAME) SELECT SEQ_SYS_ROLES.NEXTVAL,'用户','user' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_ROLES T2 WHERE T2.NAME='user');

INSERT INTO SYS_USERS (ID,SALT,USERNAME,PASSWORD,ENABLED,FULLNAME,EMAIL,CREATED_AT,UPDATED_AT)
  SELECT 1,'1bdddc10768b810af98d47fb4cf4766f','admin@pt.sisi','b92ae853d5eb3bcee49bf60839e5e78df8b40de4f43473b29de19b2bc198fee4',1,'admin@pt.sisi','ADMINISTRATOR',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP() FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_USERS T1 WHERE T1.ID=1);

DROP SEQUENCE SEQ_SYS_USERS;
CREATE SEQUENCE SEQ_SYS_USERS START WITH 2 INCREMENT BY 1;
