--初始化角色
INSERT INTO SYS_ROLES (ID,DESCRIPTION,NAME) SELECT 1,'超级管理员','admin' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_ROLES T2 WHERE T2.NAME='admin');
INSERT INTO SYS_ROLES (ID,DESCRIPTION,NAME) SELECT 2,'用户','user' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_ROLES T2 WHERE T2.NAME='user');

--初始化超级管理员和用户
INSERT INTO SYS_USERS (ID,SALT,USERNAME,PASSWORD,ENABLED,FULLNAME,EMAIL,CREATED_AT,UPDATED_AT)
  SELECT 1,'e4f85722780c2c68ddccd597bac23e81','pluto4321@163.com','1f209247dee56e7a78f03cffd4e945e9eb27d71ab96a0dff27263fcb573656cc',1,'pluto4321@163.com','大熊',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP() FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_USERS T1 WHERE T1.ID=1);
INSERT INTO SYS_USERS (ID,SALT,USERNAME,PASSWORD,ENABLED,FULLNAME,EMAIL,CREATED_AT,UPDATED_AT)
  SELECT 2,'72fc3bda25cd8e40ecc40c00c4eeafba','284839053@qq.com','74adf5bd67245490544958e5970991da0f47603fd272c636635af2152ce4371d',1,'284839053@qq.com','暖暖',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP() FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_USERS T1 WHERE T1.ID=2);


DROP SEQUENCE SEQ_SYS_ROLES;
CREATE SEQUENCE SEQ_SYS_ROLES START WITH 10 INCREMENT BY 1;
DROP SEQUENCE SEQ_SYS_USERS;
CREATE SEQUENCE SEQ_SYS_USERS START WITH 10 INCREMENT BY 1;

INSERT INTO SYS_USERS_ROLES (ROLE_ID, USER_ID)  SELECT ID,1 FROM SYS_ROLES WHERE NAME = 'admin' AND NOT EXISTS(SELECT 1 FROM SYS_USERS_ROLES WHERE USER_ID = 1) ;
INSERT INTO SYS_USERS_ROLES (ROLE_ID, USER_ID)  SELECT ID,2 FROM SYS_ROLES WHERE NAME = 'user' AND NOT EXISTS(SELECT 1 FROM SYS_USERS_ROLES WHERE USER_ID = 2) ;
--初始化资源
--用户资源
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 1,'用户列表','perms[user:list],user','/security/user/list' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/security/user/list');
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 2,'创建用户','perms[user:insert],authc','/security/user/insert' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/security/user/insert');
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 3,'修改用户','perms[user:update],authc','/security/user/update' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/security/user/update');
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 4,'删除用户','perms[user:delete],authc','/security/user/delete' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/security/user/delete');
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 5,'编辑用户','perms[user:edit],authc','/security/user/edit' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/security/user/edit');
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 6,'查看用户','perms[user:info],user','/security/user/info' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/security/user/info');
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 7,'查看头像','perms[user:portrait],user','/security/user/portrait' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/security/user/portrait');
--角色资源
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 8,'角色列表','perms[role:list],user','/security/role/list' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/security/role/list');
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 9,'创建角色','perms[role:insert],authc','/security/role/insert' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/security/role/insert');
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 10,'修改角色','perms[role:update],authc','/security/role/update' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/security/role/update');
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 11,'删除角色','perms[role:delete],authc','/security/role/delete' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/security/role/delete');
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 12,'编辑角色','perms[role:edit],authc','/security/role/edit' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/security/role/edit');
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 13,'查看角色','perms[role:info],user','/security/role/info' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/security/role/info');
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 14,'角色授权','perms[role:authority],user','/security/role/authority' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/security/role/authority');

--资源资源
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 15,'资源列表','perms[resource:list],user','/security/resource/list' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/security/resource/list');
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 16,'创建资源','perms[resource:insert],authc','/security/resource/insert' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/security/resource/insert');
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 17,'修改资源','perms[resource:update],authc','/security/resource/update' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/security/resource/update');
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 18,'删除资源','perms[resource:delete],authc','/security/resource/delete' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/security/resource/delete');
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 19,'编辑资源','perms[resource:edit],authc','/security/resource/edit' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/security/resource/edit');
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 20,'查看资源','perms[resource:info],user','/security/resource/info' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/security/resource/info');

--菜单资源
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 21,'菜单列表','perms[menu:list],user','/security/menu/list' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/security/menu/list');
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 22,'创建菜单','perms[menu:insert],authc','/security/menu/insert' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/security/menu/insert');
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 23,'修改菜单','perms[menu:update],authc','/security/menu/update' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/security/menu/update');
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 24,'删除菜单','perms[menu:delete],authc','/security/menu/delete' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/security/menu/delete');
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 25,'编辑菜单','perms[menu:edit],authc','/security/menu/edit' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/security/menu/edit');
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 26,'查看菜单','perms[menu:info],user','/security/menu/info' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/security/menu/info');

--我的信息
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 27,'我的信息','perms[my:info],user','/security/my/info' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/security/my/info');
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 28,'修改信息','perms[my:update],authc','/security/my/update' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/security/my/update');
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 29,'编辑信息','perms[my:edit],authc','/security/my/edit' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/security/my/edit');


DROP SEQUENCE SEQ_SYS_RESOURCES;
CREATE SEQUENCE SEQ_SYS_RESOURCES START WITH 50 INCREMENT BY 1;
--参数设置资源
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 30,'我的参数','perms[param:info]','/search/param/info' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/search/param/info');
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 31,'创建参数','perms[param:insert],authc','/search/param/insert' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/search/param/insert');
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 32,'修改参数','perms[param:update],authc','/search/param/update' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/search/param/update');
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 33,'编辑参数','perms[param:edit],authc','/search/param/edit' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/search/param/edit');
--日报搜索资源
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 34,'日报搜索','perms[daily:index],auth','/search/daily/index' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/search/daily/index');
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 35,'日报检索','perms[daily:search],auth','/search/daily/search' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/search/daily/search');
--研报搜索资源
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 36,'研报搜索','perms[research:index],auth','/search/research/index' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/search/research/index');
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 37,'研报检索','perms[research:search],auth','/search/research/search' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/search/research/search');
--数据字典资源
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 38,'数据字典列表','perms[dictionary:list],auth','/system/dictionary/list' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/system/dictionary/list');
--系统信息资源
INSERT INTO SYS_RESOURCES(ID,NAME,PERMISSION,VALUE) SELECT 39,'系统信息','perms[system-info:list],auth','/system/system-info/list' FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_RESOURCES WHERE VALUE='/system/system-info/list');
--初始化菜单
/*
1.搜索管理
	1.1参数设置
	1.2日报搜索
	1.3研报搜索
*/
INSERT INTO SYS_MENUS(ID,INDEXNO,ENABLED,ENTRY,ICON,NAME,PARENT_ID)
SELECT 1,1,1,NULL,'glyphicon glyphicon-briefcase','搜索管理',NULL FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_MENUS WHERE NAME='搜索管理');
INSERT INTO SYS_MENUS(ID,INDEXNO,ENABLED,ENTRY,ICON,NAME,PARENT_ID)
SELECT 2,1,1,'/search/param/info','glyphicon glyphicon-leaf','我的参数',(SELECT ID FROM SYS_MENUS WHERE NAME='搜索管理') FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_MENUS WHERE NAME='我的参数');
INSERT INTO SYS_MENUS_RESOURCES(MENU_ID,RESOURCE_ID)
SELECT 2,ID FROM SYS_RESOURCES WHERE VALUE LIKE '/search/param/%' AND NOT EXISTS(SELECT 1 FROM SYS_MENUS_RESOURCES WHERE MENU_ID =2);
INSERT INTO SYS_MENUS(ID,INDEXNO,ENABLED,ENTRY,ICON,NAME,PARENT_ID)
SELECT 3,2,1,'/search/daily/index','glyphicon glyphicon-search','日报搜索',(SELECT ID FROM SYS_MENUS WHERE NAME='搜索管理') FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_MENUS WHERE NAME='日报搜索');
INSERT INTO SYS_MENUS_RESOURCES(MENU_ID,RESOURCE_ID)
SELECT 3,ID FROM SYS_RESOURCES WHERE VALUE LIKE '/search/daily/%' AND NOT EXISTS(SELECT 1 FROM SYS_MENUS_RESOURCES WHERE MENU_ID =3);
INSERT INTO SYS_MENUS(ID,INDEXNO,ENABLED,ENTRY,ICON,NAME,PARENT_ID)
SELECT 4,3,1,'/search/research/index','glyphicon glyphicon-book','研报搜索',(SELECT ID FROM SYS_MENUS WHERE NAME='搜索管理') FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_MENUS WHERE NAME='研报搜索');
INSERT INTO SYS_MENUS_RESOURCES(MENU_ID,RESOURCE_ID)
SELECT 4,ID FROM SYS_RESOURCES WHERE VALUE LIKE '/search/research/%' AND NOT EXISTS(SELECT 1 FROM SYS_MENUS_RESOURCES WHERE MENU_ID =4);
/*
2.权限管理
	2.1用户管理
	2.2角色管理
	2.3资源管理
	2.4菜单管理
*/
INSERT INTO SYS_MENUS(ID,INDEXNO,ENABLED,ENTRY,ICON,NAME,PARENT_ID)
SELECT 5,2,1,NULL,'glyphicon glyphicon-lock','权限管理',NULL FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_MENUS WHERE NAME='权限管理');
INSERT INTO SYS_MENUS(ID,INDEXNO,ENABLED,ENTRY,ICON,NAME,PARENT_ID)
SELECT 6,1,1,'/security/user/list','glyphicon glyphicon-user','用户管理',(SELECT ID FROM SYS_MENUS WHERE NAME='权限管理') FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_MENUS WHERE NAME='用户管理');
INSERT INTO SYS_MENUS_RESOURCES(MENU_ID,RESOURCE_ID)
SELECT 6,ID FROM SYS_RESOURCES WHERE VALUE LIKE '/security/user/%'  AND NOT EXISTS(SELECT 1 FROM SYS_MENUS_RESOURCES WHERE MENU_ID =6);
INSERT INTO SYS_MENUS(ID,INDEXNO,ENABLED,ENTRY,ICON,NAME,PARENT_ID)
SELECT 7,2,1,'/security/role/list','glyphicon glyphicon-folder-close','角色管理',(SELECT ID FROM SYS_MENUS WHERE NAME='权限管理') FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_MENUS WHERE NAME='角色管理');
INSERT INTO SYS_MENUS_RESOURCES(MENU_ID,RESOURCE_ID)
SELECT 7,ID FROM SYS_RESOURCES WHERE VALUE LIKE '/security/role/%' AND NOT EXISTS(SELECT 1 FROM SYS_MENUS_RESOURCES WHERE MENU_ID =7);
INSERT INTO SYS_MENUS(ID,INDEXNO,ENABLED,ENTRY,ICON,NAME,PARENT_ID)
SELECT 8,3,1,'/security/resource/list','glyphicon glyphicon-road','资源管理',(SELECT ID FROM SYS_MENUS WHERE NAME='权限管理') FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_MENUS WHERE NAME='资源管理');
INSERT INTO SYS_MENUS_RESOURCES(MENU_ID,RESOURCE_ID)
SELECT 8,ID FROM SYS_RESOURCES WHERE VALUE LIKE '/security/resource/%' AND NOT EXISTS(SELECT 1 FROM SYS_MENUS_RESOURCES WHERE MENU_ID =8);
INSERT INTO SYS_MENUS(ID,INDEXNO,ENABLED,ENTRY,ICON,NAME,PARENT_ID)
SELECT 9,4,1,'/security/menu/list','glyphicon glyphicon-th-list','菜单管理',(SELECT ID FROM SYS_MENUS WHERE NAME='权限管理') FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_MENUS WHERE NAME='菜单管理');
INSERT INTO SYS_MENUS_RESOURCES(MENU_ID,RESOURCE_ID)
SELECT 9,ID FROM SYS_RESOURCES WHERE VALUE LIKE '/security/menu/%' AND NOT EXISTS(SELECT 1 FROM SYS_MENUS_RESOURCES WHERE MENU_ID =9);
/*
3.系统管理
	3.1数据字典
	3.2系统信息
*/
INSERT INTO SYS_MENUS(ID,INDEXNO,ENABLED,ENTRY,ICON,NAME,PARENT_ID)
SELECT 10,3,1,NULL,'glyphicon glyphicon-file','系统管理',NULL FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_MENUS WHERE NAME='系统管理');
INSERT INTO SYS_MENUS(ID,INDEXNO,ENABLED,ENTRY,ICON,NAME,PARENT_ID)
SELECT 11,1,1,'/system/dictionary/list','glyphicon glyphicon-user','数据字典',(SELECT ID FROM SYS_MENUS WHERE NAME='系统管理') FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_MENUS WHERE NAME='数据字典');
INSERT INTO SYS_MENUS_RESOURCES(MENU_ID,RESOURCE_ID)
SELECT 11,ID FROM SYS_RESOURCES WHERE VALUE LIKE '/system/dictionary/%' AND NOT EXISTS(SELECT 1 FROM SYS_MENUS_RESOURCES WHERE MENU_ID =11);
INSERT INTO SYS_MENUS(ID,INDEXNO,ENABLED,ENTRY,ICON,NAME,PARENT_ID)
SELECT 12,2,1,'/system/system-info/list','glyphicon glyphicon-user','系统信息',(SELECT ID FROM SYS_MENUS WHERE NAME='系统管理') FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM SYS_MENUS WHERE NAME='系统信息');
INSERT INTO SYS_MENUS_RESOURCES(MENU_ID,RESOURCE_ID)
SELECT 12,ID FROM SYS_RESOURCES WHERE VALUE LIKE '/system/system-info/%' AND NOT EXISTS(SELECT 1 FROM SYS_MENUS_RESOURCES WHERE MENU_ID =12);

DROP SEQUENCE SEQ_SYS_MENUS;
CREATE SEQUENCE SEQ_SYS_MENUS START WITH 50 INCREMENT BY 1;

--授权admin可以使用所有菜单,user只能使用搜索设置
INSERT INTO SYS_ROLES_RESOURCES(ROLE_ID,RESOURCE_ID)
SELECT A.ID,B.ID FROM SYS_ROLES A,SYS_RESOURCES B WHERE A.NAME='admin' AND NOT EXISTS(SELECT 1 FROM SYS_ROLES_RESOURCES WHERE ROLE_ID =1);
INSERT INTO SYS_ROLES_RESOURCES(ROLE_ID,RESOURCE_ID)
SELECT A.ID,B.ID FROM SYS_ROLES A,SYS_RESOURCES B
WHERE A.NAME='user' AND B.ID IN (SELECT ID FROM SYS_RESOURCES WHERE VALUE like '/search/%' OR VALUE LIKE '/security/my/%')
AND NOT EXISTS(SELECT 1 FROM SYS_ROLES_RESOURCES WHERE ROLE_ID =2);
